build: false

environment:
  MINICONDA: C:\Miniconda37-x64
  matrix:
    - PYTHON_VERSION: 3.7
    - PYTHON_VERSION: 3.8
    - PYTHON_VERSION: 3.9
      
init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # Issues have been encountered with installing numpy and scipy on
  # AppVeyor e.g.
  # http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/
  # Miniconda is recommended as the way to install these. See also:
  # https://github.com/appveyor/ci/issues/359
  # The following adopts approaches suggested in the above links.
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION%"
  - activate test-environment

  # Majority of dependencies can be installed with Anaconda
  - conda install -c conda-forge "numpy>=1.14" scipy matplotlib sympy
    networkx nose h5py pandas mkl pydot mock cython

  - pip install python-libsbml

  - conda install -c alubbock pygraphviz bionetgen atomizer kappa stochkit-lite
test_script:
  - python setup.py nosetests -a "!gpu"
